apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zot-image-pull-secret.yaml
  - image-repository-autodock-vina.yaml
  - image-repository-jupyter-chem.yaml
  - image-policy-autodock-vina.yaml
  - image-policy-jupyter-chem.yaml
  - image-repository-result-writer.yaml
  - image-policy-result-writer.yaml
  - image-repository-khemeia-controller.yaml
  - image-policy-khemeia-controller.yaml
  - image-repository-khemeia-result-writer.yaml
  - image-policy-khemeia-result-writer.yaml
  - image-repository-esmfold.yaml
  - image-policy-esmfold.yaml
  - image-repository-ddg.yaml
  - image-policy-ddg.yaml
  - image-update-automation.yaml
