apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zot-pull-secret.yaml
  - image-repository.yaml
  - image-policy.yaml
  - image-update-automation.yaml
  - image-repository-frontend.yaml
  - image-policy-frontend.yaml
  - image-update-automation-frontend.yaml
  - image-repository-demo-mcp.yaml
  - image-policy-demo-mcp.yaml
  - image-repository-demo-sites.yaml
  - image-policy-demo-sites.yaml
  - image-repository-voice-agent.yaml
  - image-policy-voice-agent.yaml
  - image-repository-site-tracker.yaml
  - image-policy-site-tracker.yaml
  - image-repository-arete-tutoring.yaml
  - image-policy-arete-tutoring.yaml
